version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sqli-part1
    container_name: sqli-part1-app
    restart: always
    ports:
      - "81:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: sqli-part1-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sqli
      MYSQL_PASSWORD: sqli
      MYSQL_DATABASE: sqli
    volumes:
      - ./db:/docker-entrypoint-initdb.d
